UPDATE article SET DESIGNATION = UPPER(DESIGNATION) WHERE PRIX > 10;
UPDATE article SET DESIGNATION = LOWER(DESIGNATION) WHERE ID = 2;
UPDATE article INNER JOIN fournisseur ON ID_FOU = fournisseur.ID SET PRIX = PRIX * 1.1 WHERE fournisseur.NOM = "FDM SA";